### ISSUE TITLE
Have better names for config retries and timeout

### ISSUE THREAD

**Issue by jossjacobo** [willowtreeapps/conductor-mobile#10]
Right now the config fields are not very descriptive of what they actually do. `retries` is essentially how long you want the implicit wait times to be (i.e. `retries = 10` will make locomotive wait and search for 10 seconds for something on the screen. `timeout` is how long we allow for appium to work on requests (i.e `timeout = 5` the test will wait for 5 seconds on every appium command like "search for element" or "get a screenshot").

**Comment by aaron-goff** [comment]
@jossjacobo @mrk-han  thinking about tackling this --
how does `timeout` -> `appiumRequestTimeout` and `retries` -> `implicitWaitTimeout` sound?
