### ISSUE TITLE
Android Device Log

### ISSUE THREAD

**Issue by ashby-bowles** [willowtreeapps/conductor-mobile#11]
Add device logging for each test. This can be implemented with ADB library as seen in 

https://github.com/ashby-bowles/UITestLib

**Comment by mrk-han** [comment]
@ashby-bowles Would you mind giving access to that repo / making it public? It is 404'ing. If not I can close this ticket

**Comment by ashby-bowles** [comment]
@mrk-han weird I'm not seeing it either. im not sure why i would've removed it...but i'll go ahead and close this down
