### ISSUE TITLE
[FEATURE] Make performSwipe more generic, allowing for different TouchActions and custom x and y coordinates

### ISSUE THREAD

**Issue by aaron-goff** [willowtreeapps/conductor-mobile#125]
**Is your feature request related to a problem? Please describe.**
`performSwipe` method in `Locomotive.java` currently is pretty cookie cutter and doesn't allow for much customization, including the TouchAction `longPress()` or changing the dimensions of where you'd like the swipe to be performed.

**Describe the solution you'd like**
I'd like to generalize the `performSwipe()` method to allow for a `longPress()` instead of just `press()`.
Id like to generalize the `performSwipe()` method to allow for x and y coordinate input, so that swipes are not tied to a specific element.
**Additional context**
The main use case, for Synchrony right now, is the ability to perform an automated "Pull to Refresh" action. This action needs a `longPress()` and the ability specify a starting/finishing x and y (because of headers, split screens, etc.)

Rough stab at changes for allowing longPress
```
private Locomotive performSwipe(SwipeElementDirection direction, boolean isLongPress, WebElement element, By by, float percentage) {
```
```
TouchAction swipe;
if (!isLongPress) {
      swipe = new TouchAction(getAppiumDriver())
              .press(point(from.getX(), from.getY()))                 
              .waitAction(waitOptions(ofMillis(SWIPE_DURATION_MILLIS)))
              .moveTo(point(to.getX(), to.getY()))
              .release();
} else {
      swipe = new TouchAction(getAppiumDriver())
               .longPress(point(from.getX(), from.getY()))
               .waitAction(waitOptions(ofMillis(SWIPE_DURATION_MILLIS)))
               .moveTo(point(to.getX(), to.getY()))
               .release();
}
swipe.perform();
```
```
private Locomotive performSwipe(SwipeElementDirection direction, WebElement element, By by, float percentage) {
        return performSwipe(direction, false, element, by, percentage);
    }

private Locomotive performLongPressSwipe(SwipeElementDirection direction, WebElement element, By by, float percentage) {
        return performSwipe(direction, true, element, by, percentage);
    }
```

**Comment by mrk-han** [comment]
This would also address https://github.com/willowtreeapps/conductor-mobile/issues/9 perhaps?

**Comment by mrk-han** [comment]
Would https://github.com/willowtreeapps/conductor-mobile/issues/49 be able to be accounted for here?

**Comment by aaron-goff** [comment]
@mrk-han yep, I can address both #9 and #49 along with this
