### ISSUE TITLE
[BUG] README should not reference timeout/retries

### ISSUE THREAD

**Issue by aaron-goff** [willowtreeapps/conductor-mobile#134]
## The problem
README still references `timeout`/`retries`
It should instead reference `appiumRequestTimeout`/`implicitWaitTime`

## Environment

* Conductor-Mobile Version: 0.19.1

**Comment by mrk-han** [comment]
Fixed in 9b5f7eca175e31df05cf0651dcd0ca501e2805c3

**Comment by mrk-han** [comment]
Merged in #136

**Comment by mrk-han** [comment]
Fully fixed in ec5791aa9336bc2ca708ee1c434ef628734ed6d9
