### ISSUE TITLE
Unable to specify UDID with command line parameter

### ISSUE THREAD

**Issue by ashby-bowles** [willowtreeapps/conductor-mobile#36]
The command line parameter "-DconductorUdid" with env. variable does not take effect and instead uses one specified in YAML config.

**Comment by ashby-bowles** [comment]
Not sure if this is related but we also need to be able to specify the platformName on command line to be able to run iPhone and iPad simulator on teamcity

**Comment by fuzzybinary** [comment]
As we talkeda bout in slack, I think it would be better for the yaml to accept enviornment variables as part of the configuration, so you can do:

```yaml
build_server:
    deviceName: ${DEVICE_NAME}
    udid: ${DEVICE_UDID}
```

and then the build step would use 
`-DconductorCurrentSchemes:build_server`

Does that make sense?

platformName is already specifyable, you can use -DconductorPlatformName... do you mean deviceName?
