### ISSUE TITLE
screenshotOnFail no longer works when set in the config.yaml or specified in mvn script

### ISSUE THREAD

**Issue by andrewowen** [willowtreeapps/conductor-mobile#44]
screenshotOnFail is not being honored on failing tests regardless if you set it in the config.yaml file or specify it in the maven script in TeamCity.

**Comment by fuzzybinary** [comment]
Most yaml properties no longer can be set on the command line, only currentPlatform / currentSchemes, but I'll look into why screenshotOnFail isn't working.
