### ISSUE TITLE
Remove swipeX methods as they swipe the wrong direction

### ISSUE THREAD

**Issue by fuzzybinary** [willowtreeapps/conductor-mobile#48]
All of the methods that are a simple "swipeX()" (e.g. swipeUp, swipeDown, swipeLeft, swipeRight) actually use the opposite SwipeElementDirection, which is just confusing.

I'd like to replace all these methods with a simple `swipe(SwipeElementDirection direction)` method

**Comment by mrk-han** [comment]
Thinking of renaming SwipeDown to ScrollDown to match its implementation.
