### ISSUE TITLE
swipeCenterLong and swipeCenterSuperLong will swipe the same distance for UP and LEFT cases

### ISSUE THREAD

**Issue by nerdsosky** [willowtreeapps/conductor-mobile#81]
In the performSwipe function:

`case UP:`
                    `int toYUp = (int) (from.getY() - (screen.getHeight() * percentage));`
                    `toYUp = toYUp <= 0 ? 1 : toYUp; // toYUp cannot be less than 0`

For example:
swipeCenter percentage = .25
swipeCenterLong percentage = .5
swipeCenterSuperLong percentage = 1.0

so based on a 100 pixel screen:
from.getY() = 50
getHeight() = 100

toYUP = 50 - (100 * .5)

toYUP will always equal 0 or less for Long and SuperLong variants and then be set to 1 in the next line

**Comment by aaron-goff** [comment]
@nerdsosky Would changing the `fromY` for swipeCenterSuperLong resolve your issue?
