### ISSUE TITLE
Need a swipe method that is near the far right/left edges 

### ISSUE THREAD

**Issue by Jared1048** [willowtreeapps/conductor-mobile#9]
This would be helpful in swiping to the "next" page. It requires a long swipe from the edge

**Comment by andrewowen** [comment]
@Jared1048 0.8.5 has a swipeCornerLong and swipeCornerSuperLong method now that allows swiping left and right as well as up and down. Hopefully this solves this and we can close this

**Comment by fuzzybinary** [comment]
@Jared1048 and I have talked about it and I'm thinking a good generalized approach, as opposed to doing tons of special case methods, is to have a method `swipePercent(Point from, Point to, int duration)`

This would take from / to coordinates and using information about the device perform a swipe from a percent location to a percent location. This could also simplify conductor's code internally which would be nice.

**Comment by aaron-goff** [comment]
This was resolved in #127 , as well as being pretty similar to #125.

We now have a method that can take in exact Point coordinates for their From/To locations.
